# Generated by Django 2.2.4 on 2019-08-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tutorial_content',
            new_name='project_content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tutorial_published',
            new_name='project_published',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tutorial_title',
            new_name='project_title',
        ),
    ]
