# Generated by Django 2.2.4 on 2019-08-13 12:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190812_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_github_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_view_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 14, 5, 33, 936146), verbose_name='date published'),
        ),
    ]
