# Generated by Django 2.2.4 on 2019-08-13 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190813_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_github_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_view_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 14, 9, 51, 626134), verbose_name='date published'),
        ),
    ]
