# Generated by Django 2.2.4 on 2019-08-13 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190813_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_github_url',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='project_view_url',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 14, 32, 37, 454426), verbose_name='date published'),
        ),
    ]
