# Generated by Django 2.2.4 on 2019-08-13 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190813_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_github_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 14, 37, 39, 757869), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_view_url',
            field=models.CharField(max_length=200),
        ),
    ]
