# Generated by Django 2.2.4 on 2019-08-13 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190813_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_view_url',
            new_name='project_slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 16, 1, 4, 703634), verbose_name='date published'),
        ),
    ]
