# Generated by Django 2.2.4 on 2019-08-13 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190813_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 17, 6, 47, 654506), verbose_name='date published'),
        ),
    ]
