# Generated by Django 2.2.4 on 2019-08-14 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190814_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 20, 51, 1, 794437), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.CharField(default='/materials/images/no_image.png', max_length=200),
        ),
    ]
