# Generated by Django 2.2.4 on 2019-08-14 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190814_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 21, 0, 45, 498067), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.CharField(default='images/no_image.png', max_length=200),
        ),
    ]
