# Generated by Django 2.2.4 on 2019-08-14 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190814_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_github_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 22, 58, 36, 897504), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_slug',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_thumbnail',
            field=models.CharField(default='no_image', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=100),
        ),
    ]
