# Generated by Django 2.2.4 on 2019-08-15 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190814_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 16, 14, 54, 924499), verbose_name='date published'),
        ),
    ]
