# Generated by Django 2.2.4 on 2019-08-20 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190815_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 21, 11, 59, 895088), verbose_name='date published'),
        ),
    ]
